#!/bin/bash
# Update or create an .ipynb notebook from a text notebook generated by Jupytext.

set -euo pipefail

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "Usage: bash scripts/update_ipynb_from_text.sh <notebook.py> [target.ipynb]" >&2
    exit 1
fi

input_text="$1"
target_ipynb="${2:-${input_text%.py}.ipynb}"

if [ ! -f "$input_text" ]; then
    echo "Input text notebook not found: $input_text" >&2
    exit 1
fi

if ! command -v jupytext >/dev/null 2>&1; then
    echo "jupytext is required but was not found in PATH" >&2
    exit 1
fi

if [ -f "$target_ipynb" ]; then
    tmp_dir="$(mktemp -d)"
    trap 'rm -rf "$tmp_dir"' EXIT
    tmp_base="$(basename "$target_ipynb" .ipynb)"
    tmp_input="$tmp_dir/$tmp_base.py"
    tmp_ipynb="$tmp_dir/$tmp_base.ipynb"
    cp "$target_ipynb" "$tmp_ipynb"
    cp "$input_text" "$tmp_input"
    (
        cd "$tmp_dir"
        jupytext --update --to notebook "$(basename "$tmp_input")"
    )
    mv "$tmp_ipynb" "$target_ipynb"
    trap - EXIT
    rm -rf "$tmp_dir"
    echo "Updated existing notebook: $target_ipynb"
else
    jupytext --to notebook --output "$target_ipynb" "$input_text"
    echo "Created new notebook: $target_ipynb"
fi
